pytucanos: fix for numpy >= 2.4
There error was:

  File "pytucanos/mesh.py", line 56, in __plot_boundary
    ax.plot(X, Y, c="C%d" % i, label=repr(t))
                    ~~~~~~^~~
TypeError: %d format: a real number is required, not numpy.ndarray